import type { LogicBlock } from './mathTypes'

export type MathComponentCatalogItem = {
  mathComponent: string
  title: string
  blocks: string[]
  block: LogicBlock
}

export const MATH_COMPONENT_CATALOG: MathComponentCatalogItem[] = [
  {
    mathComponent: 'TotalAmountComponent',
    title: 'TotalAmountComponent',
    blocks: ['求总量'],
    block: {
      step: 1,
      type: '求总量',
      component: 'TotalAmountComponent',
      math_object: '每份8个，共3份',
      visual_object: '小熊分糖',
    },
  },
  {
    mathComponent: 'PartitionComponent',
    title: 'PartitionComponent',
    blocks: ['求每份数', '求份数'],
    block: {
      step: 1,
      type: '求份数',
      component: 'PartitionComponent',
      math_object: '220瓶橙汁，每次24瓶',
      visual_object: '橙汁、搬运',
    },
  },
  {
    mathComponent: 'SumComponent',
    title: 'SumComponent',
    blocks: ['求和'],
    block: {
      step: 1,
      type: '求和',
      component: 'SumComponent',
      math_object: '15本，20本，12本',
      visual_object: '图书、合并',
    },
  },
  {
    mathComponent: 'AverageComponent',
    title: 'AverageComponent',
    blocks: ['平均数'],
    block: {
      step: 1,
      type: '平均数',
      component: 'AverageComponent',
      math_object: '总身高60厘米，3人',
      visual_object: '柱状图、均分',
    },
  },
  {
    mathComponent: 'FractionComponent',
    title: 'FractionComponent',
    blocks: ['分数意义', '求部分量'],
    block: {
      step: 1,
      type: '分数意义',
      component: 'FractionComponent',
      math_object: '把12个苹果平均分成4份，取其中3份',
      visual_object: '苹果、分数条',
    },
  },
  {
    mathComponent: 'PatternCycleComponent',
    title: 'PatternCycleComponent',
    blocks: ['周期规律', '余数'],
    block: {
      step: 1,
      type: '求第N个',
      component: 'PatternCycleComponent',
      math_object: '圆、三角、方块循环',
      visual_object: '周期图形、扫描',
      props: {
        type: '',
        targetN: 1,
        cycleLength: 1,
        cycleItems: ['', ''],
        fullCycles: 1,
        perCycleCount: 1,
        remainderCount: 1,
        buttonText: '',
      },
    },
  },
  {
    mathComponent: 'DifferenceComponent',
    title: 'DifferenceComponent',
    blocks: ['求差', '比较大小'],
    block: {
      step: 1,
      type: '求差',
      component: 'DifferenceComponent',
      math_object: '两盒彩笔分别有18支和12支',
      visual_object: '彩笔、对比',
    },
  },
  {
    mathComponent: 'RemainderComponent',
    title: 'RemainderComponent',
    blocks: ['求剩余'],
    block: {
      step: 1,
      type: '求剩余',
      component: 'RemainderComponent',
      math_object: '买了30颗糖，分出去18颗',
      visual_object: '糖果、分发',
    },
  },
  {
    mathComponent: 'MultipleComponent',
    title: 'MultipleComponent',
    blocks: ['求倍数', '求一个数的几倍'],
    block: {
      step: 1,
      type: '求倍数',
      component: 'MultipleComponent',
      math_object: '3盒彩纸，每盒6张',
      visual_object: '彩纸、重复',
    },
  },
  {
    mathComponent: 'ReverseComponent',
    title: 'ReverseComponent',
    blocks: ['逆运算', '倒推'],
    block: {
      step: 1,
      type: '逆运算',
      component: 'ReverseComponent',
      math_object: '结果为18，先加5',
      visual_object: '流程图、回推',
    },
  },
  {
    mathComponent: 'CompareComponent',
    title: 'CompareComponent',
    blocks: ['大小比较', '够不够'],
    block: {
      step: 1,
      type: '大小比较',
      component: 'CompareComponent',
      math_object: '18和12比较',
      visual_object: '天平、比较',
    },
  },
  {
    mathComponent: 'EstimateComponent',
    title: 'EstimateComponent',
    blocks: ['四舍五入', '估算'],
    block: {
      step: 1,
      type: '四舍五入',
      component: 'EstimateComponent',
      math_object: '73靠近70',
      visual_object: '数轴、磁吸',
    },
  },
  {
    mathComponent: 'NumberSenseComponent',
    title: 'NumberSenseComponent',
    blocks: ['位数估算', '数感'],
    block: {
      step: 1,
      type: '位数估算',
      component: 'NumberSenseComponent',
      math_object: '432 × 21',
      visual_object: '雷达、位数槽',
    },
  },
  {
    mathComponent: 'UnitConvertComponent',
    title: 'UnitConvertComponent',
    blocks: ['统一时间单位', '统一长度单位', '统一面积单位', '统一质量单位'],
    block: {
      step: 1,
      type: '统一时间单位',
      component: 'UnitConvertComponent',
      math_object: '2小时30分和150分钟',
      visual_object: '时钟、换算',
    },
  },
  {
    mathComponent: 'PointSegmentComponent',
    title: 'PointSegmentComponent',
    blocks: ['求间隔段数', '求棵数（两端都种）', '求棵数（封闭图形）', '识别为封闭图形植树'],
    block: {
      step: 1,
      type: '求间隔段数',
      component: 'PointSegmentComponent',
      math_object: '两端都栽树，中间隔4米',
      visual_object: '点线、树木',
    },
  },
  {
    mathComponent: 'PriceQuantityComponent',
    title: 'PriceQuantityComponent',
    blocks: ['求总价', '求单价', '求数量'],
    block: {
      step: 1,
      type: '求总价',
      component: 'PriceQuantityComponent',
      math_object: '4盒彩笔，每盒12元',
      visual_object: '购物、价签',
    },
  },
  {
    mathComponent: 'DistanceSpeedTimeComponent',
    title: 'DistanceSpeedTimeComponent',
    blocks: ['求路程', '求速度', '求时间', '求经过时间'],
    block: {
      step: 1,
      type: '求路程',
      component: 'DistanceSpeedTimeComponent',
      math_object: '每小时5千米，走了3小时',
      visual_object: '路线、公交',
    },
  },
  {
    mathComponent: 'GeometryAreaComponent',
    title: 'GeometryAreaComponent',
    blocks: ['求长方形面积', '求正方形面积', '求长方形周长', '求正方形周长', '求剩余部分面积', '求各部分面积之和', '求平移后周长', '分割成标准图形', '补成完整图形', '识别为L形', '识别为凹形'],
    block: {
      step: 1,
      type: '求长方形面积',
      component: 'GeometryAreaComponent',
      math_object: '长方形长8米宽5米',
      visual_object: '图形、面积',
    },
  },
  {
    mathComponent: 'TimeComponent',
    title: 'TimeComponent',
    blocks: ['求经过时间', '求开始时刻', '求结束时刻'],
    block: {
      step: 1,
      type: '求经过时间',
      component: 'TimeComponent',
      math_object: '出发时刻9:00到11:15的时间差',
      visual_object: '钟表',
    },
  },
  {
    mathComponent: 'AgeComponent',
    title: 'AgeComponent',
    blocks: ['年龄差', '倍数契合'],
    block: {
      step: 1,
      type: '年龄推演',
      component: 'AgeComponent',
      math_object: '甲12岁，乙9岁',
      visual_object: '双轴、年龄条',
    },
  },
  {
    mathComponent: 'RoundingComponent',
    title: 'RoundingComponent',
    blocks: ['进一法取整', '去尾法取整'],
    block: {
      step: 1,
      type: '进一法取整',
      component: 'RoundingComponent',
      math_object: '商9余4',
      visual_object: '搬运次数',
    },
  },
  {
    mathComponent: 'GenericLogicComponent',
    title: 'GenericLogicComponent',
    blocks: ['其他逻辑块'],
    block: {
      step: 1,
      type: '通用逻辑块',
      component: 'GenericLogicComponent',
      math_object: '其他关系',
      visual_object: '通用素材',
    },
  },
]
